# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
      

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install AngleSharp
      run: dotnet add package AngleSharp
    #- name: Restore dependencies
    #  run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.os }}
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: EkCC-${{ matrix.os }}
        path: BetterEK/bin/Release/publish/*
